### PR TITLE
Updates std Library to Latest Commit -  f4a71b1

### PR DESCRIPTION
**Pull request by HideyoshiNakazone**
Created this merge request to update the STD Sub module to the latest current commit.

### CODE REVIEW

**Comment by HideyoshiNakazone** [comment]
Closed because errors were found, i'll reopen after fixed

**Comment by HideyoshiNakazone** [comment]
The fix replaces `stb_image_resize.h` -> `stb_image_resize2.h`

**Comment by gracicot** [comment]
Thank you!

**Comment by HideyoshiNakazone** [comment]
Thank you! 👍

**Pull request merged**
